Тестовое задание для frontend'a
smenateam/assignments pull request #2
Opened 2019-09-04 11:47 UTC by salmasov

2019-09-04 12:01 UTC, archived001 reviewed
ну вот историю с 404 поправить и вроде как норм

2019-09-04 12:01 UTC, archived001 commented on frontend/README.md
> +### 404 - регистрация не удалась
400?

2019-09-04 12:01 UTC, archived001 commented on frontend/README.md
> +### 404 - не удалось получить информацию
400

2019-09-04 12:01 UTC, archived001 commented on frontend/app.js
> +    res.status(404).json({
400

2019-09-04 12:01 UTC, archived001 commented on frontend/app.js
> +    res.status(404).json({
400

2019-09-04 12:22 UTC, salmasov commented
Поправил 404->400 ошибки сверху

2019-09-04 12:26 UTC, graberzz commented on frontend/README.md
> +Задача - реализовать SPA приложение, в котором пользователь может зарегистрироваться и просмотреть личную информацию о себе
```suggestion
Задача - реализовать SPA приложение, в котором пользователь может зарегистрироваться и просмотреть личную информацию о себе.
```

2019-09-04 12:29 UTC, hnkisdead requested changes

2019-09-04 12:29 UTC, subv13 commented on frontend/README.md
> +| success | Boolean | статус запроса | true                                   |
Мне кажется статус кодов хватит для понимания что ок или не ок, зачем ещё status?

2019-09-04 12:29 UTC, graberzz commented on frontend/README.md
> +Так же должен быть предусмотрен переход на страницу `/register` в виде кнопки
```suggestion
Также должен быть предусмотрен переход на страницу `/register` в виде кнопки
```

2019-09-04 12:30 UTC, graberzz commented on frontend/README.md
> +Так же должен быть предусмотрен переход на страницу `/login` в виде кнопки
```suggestion
Так же должен быть предусмотрен переход на страницу `/login` в виде кнопки
```
```suggestion
Также должен быть предусмотрен переход на страницу `/login` в виде кнопки.
```

2019-09-04 12:31 UTC, graberzz commented on frontend/README.md
> +Желательно оформить в виде карточки
```suggestion
Желательно оформить в виде карточки.
```

2019-09-04 12:36 UTC, graberzz commented on frontend/README.md
> +В результате в коноли получаем output
```suggestion
В результате в консоли получаем output:
```

2019-09-04 12:38 UTC, graberzz commented on frontend/README.md
> +- По-умолчанию api запускается по адресу `http://localhost:8080`
```suggestion
- По умолчанию api запускается по адресу `http://localhost:8080`
```

2019-09-04 12:50 UTC, graberzz commented on frontend/package.json
> +    "mongoose": "^5.6.12",
😮

2019-09-04 13:17 UTC, graberzz commented on frontend/README.md
> +Для простоты разработки данного приложения виде backend-части в данном репозитории представлен файл `app.js`. backend-часть дополнять и изменять `не нужно`. Процесс запуска api на вашей машине описан
```suggestion
Для простоты разработки данного приложения в виде backend-части в данном репозитории представлен файл `app.js`. backend-часть дополнять и изменять `не нужно`. Процесс запуска api на вашей машине описан ниже.
```

2019-09-05 06:41 UTC, graberzz commented on frontend/README.md
> +Авторизация и регистрация на backend-части реализована через `jwt-token`.
```suggestion
Авторизация и регистрация на backend-части реализована через [JSON Web Token](https://ru.wikipedia.org/wiki/JSON_Web_Token).
```

2019-09-05 06:43 UTC, graberzz commented on frontend/package.json
> +  "name": "express-jwt-auth",
палево!!! 😱

2019-09-05 06:46 UTC, graberzz commented on frontend/README.md
> +- Убедитесь, что у вас стоит последняя node LTS версии https://nodejs.org/en/
```suggestion
- Убедитесь, что у вас стоит последняя node LTS версии https://nodejs.org/en/
```
```suggestion
- Убедитесь, что у вас стоит Node.js последней LTS версии: https://nodejs.org/en/
```

2019-09-05 06:47 UTC, graberzz commented on frontend/README.md
> +1. Убедитесь, что у вас стоит последняя node LTS версии. Ссылка для скачивания: https://nodejs.org/en/
дублирование кстати, хотя может чтоб наверняка..... 🤔

2019-09-05 06:50 UTC, graberzz commented on frontend/README.md
> +2. В терминале/консоли открыть папку [frontend/](frontend/)
терминал или консоль таки??? в других местах везде консоль употребляется... надо бы чтоб путаницы не возникало, а то мало ли....

2019-09-05 06:52 UTC, graberzz commented on frontend/README.md
> +
Добавить пункт про то что написанные тесты будут плюсом

2019-09-05 06:56 UTC, graberzz commented on frontend/README.md
> +При выполнении запросов к api в консоли будут возникать логи, удобно для тестирования приложения
```suggestion
При выполнении запросов к api в консоли будут возникать логи, удобно для тестирования приложения
```
```suggestion
При выполнении запросов к api в консоли будут возникать логи, удобно для тестирования приложения.
```

2019-09-05 06:57 UTC, graberzz commented on frontend/README.md
> +1. Реализацию frontend-части следует делать `в отдельной папке`, а не в этом репозитории. Этот репозиторий содержит в себе только backend-часть в виде api.
Отдельном репозитории мб?

2019-09-05 07:12 UTC, graberzz commented on frontend/app.js
> +    message: "Пользователь успешно зарегестрирован"
```suggestion
    message: "Пользователь успешно зарегистрирован"
```

2019-09-05 07:13 UTC, graberzz commented on frontend/README.md
> +Если в заголовке не передавать jwt-токен, либо jwt-токен был просрочен - вернется ответ
Уточнить про заголовок.

2019-09-05 07:21 UTC, graberzz commented on frontend/app.js
> +  const { username, password } = req.body;
А валидаций совсем никаких не будет? Сейчас можно например пустые объекты вместо полей передать...

2019-09-05 07:40 UTC, graberzz commented
Возможно стоит уточнить про потухание токена.

2019-09-05 11:12 UTC, salmasov commented on frontend/README.md
> +| success | Boolean | статус запроса | true                                   |
Выпилил success'ы

2019-09-05 11:13 UTC, salmasov commented on frontend/package.json
> +    "mongoose": "^5.6.12",
Действительно, лишнее

2019-09-05 11:13 UTC, salmasov commented on frontend/package.json
> +  "name": "express-jwt-auth",
Поменял на frontent-assigment

2019-09-05 11:14 UTC, salmasov commented on frontend/README.md
> +2. В терминале/консоли открыть папку [frontend/](frontend/)
Оставил консоль

2019-09-05 11:15 UTC, salmasov commented on frontend/README.md
> +
Добавил

2019-09-05 11:19 UTC, salmasov commented on frontend/app.js
> +  const { username, password } = req.body;
Добавил валидацию на длину имени-пароля

2019-09-05 11:35 UTC, graberzz commented on frontend/README.md
> +Если в заголовке не передавать jwt-токен, либо jwt-токен был просрочен - вернется ответ
Вот тут надо расписать как токен передавать конкретнее

2019-09-05 13:17 UTC, hnkisdead requested changes

2019-09-05 13:17 UTC, subv13 commented on frontend/README.md
> +Чтобы отправить запрос с токеном нужно в Temporary Headers запроса указать заголовок `Authorization: Bearer ${токен пользователя}`
"Чтобы отправить запрос с токеном нужно указать заголовок". Temporary Headers это из Postman, никак к HTTP не относится

2019-09-05 13:17 UTC, graberzz commented on frontend/README.md
> +2. В консоли открыть папку [frontend/](frontend/)
ссылочка на 404 ведет
```suggestion
2. В консоли открыть папку `frontend`
```

2019-09-05 13:22 UTC, merged